### ISSUE TITLE
Visitors not possible to make the reservation (field colour brown)

### ISSUE THREAD

**Issue by Holdyfan** [holdybot/holdybot#1]
Hello, i am just testing the amazing Holdybot qand when making reservation from the visitor acount they remain brown
![brown](https://github.com/holdybot/holdybot/assets/164001925/53932557-5afc-4c59-986f-a9e17531e5fa)
Only once in the admin section the concrete email is maintsained under allowed user email the user is able to make the reservation. Is that an intention please? Thank you, Vendula

**Comment by tlamr** [comment]
Hello Vendula, the purpose of visitors is to have users that are included in scheduling only when confirmed by admin.
Hence, and administrator, needs to open the view in admin mode and click on (back to game) button to make them yellow.

If you wish to have all users to be able to make reservations directly, you can enable it this in settings this way as shown on the figure.
<img width="478" alt="Screenshot 2024-03-19 at 11 17 07" src="https://github.com/holdybot/holdybot/assets/34898768/c3de1d67-9060-4d55-9410-51227fdb85f9">


Cheers,
Tomas

**Comment by Holdyfan** [comment]
Thanks a lot Tomas for the fast feedback! Very much appreciated :) So I have ticked the check box, as shown below, do i sill need to fill the suffixes? 
![image](https://github.com/holdybot/holdybot/assets/164001925/219abc76-f279-45cc-bb38-d8f53bfc3f2a)

**Comment by tlamr** [comment]
Yep, you need to allow user email suffixes which will turn visitors into normal users.
Or you need to confirm reservations as an admin one by one (turning brown into yellow) by this kick-in button.
<img width="331" alt="Screenshot 2024-03-19 at 14 02 32" src="https://github.com/holdybot/holdybot/assets/34898768/3922ff25-788d-4905-baa5-0eddf59fa5b2">

**Comment by Holdyfan** [comment]
Super, diky moc. Pekny den, Vendula

**Comment by tlamr** [comment]
Happy to help, cheers! :)
